name: Go

on:
  push:
    branches:
    - master
  create:
    tags:
    - "v*"  # trigger on a new version tag

jobs:
  build:
    env:
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Build
      run: go build -v -o bin/healthcheck4dns ./...
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/bin
